# Numpy

_numpy_ é a abreviação de _numerical python_. Se trata de uma biblioteca de não nativa de _Python_ que possibilita cálculos númericos de uma forma bastante flexível e eficiente. Depois de instalar _numpy_, importamos a biblioteca e damos um apelido para ela chamando `import numpy as np` onde a palavra reservada `as` é opicional e o que vem em seguida é o apelido que damos para a biblioteca.

Para instalar _numpy_ direto do _jupyter_ basta chamar `!conda install numpy` se você utiliza Anaconda ou `!pip install numpy` caso contrário. Se for instalar direto do _prompt_ omita o ponto de exclamação no início.

In [1]:
import numpy as np

É uma convenção chamar _numpy_ de _np_.

Para instalar bibliotecas direto no _Juypyter_:

* !conda install <nome da biblioteca>  
* !pip install <nome da biblioteca>
    
O principal tipo utilizdo pelo _np_ é os `ndarray`. Um jeito de pensar nelas são matrizes de tamanhos e formas flexíveis. São bem parecidas com as listas porém mais eficientes no trato da memória.

In [5]:
type(np.arange(10))

numpy.ndarray

In [7]:
array_1d = np.array([1, 2, 3])
array_1d

array([1, 2, 3])

In [8]:
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
array_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
array_2d.shape

(2, 3)

In [13]:
array_1d_uns = np.ones(10)
array_1d_uns

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [16]:
array_2d_uns = np.ones((5, 10))
array_2d_uns

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [17]:
array_3d_uns = np.ones((2, 5, 10))
array_3d_uns

array([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]])

In [18]:
np.zeros((2, 5, 10))

array([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]])

In [22]:
np.full((2, 5, 10), 20)

array([[[20, 20, 20, 20, 20, 20, 20, 20, 20, 20],
        [20, 20, 20, 20, 20, 20, 20, 20, 20, 20],
        [20, 20, 20, 20, 20, 20, 20, 20, 20, 20],
        [20, 20, 20, 20, 20, 20, 20, 20, 20, 20],
        [20, 20, 20, 20, 20, 20, 20, 20, 20, 20]],

       [[20, 20, 20, 20, 20, 20, 20, 20, 20, 20],
        [20, 20, 20, 20, 20, 20, 20, 20, 20, 20],
        [20, 20, 20, 20, 20, 20, 20, 20, 20, 20],
        [20, 20, 20, 20, 20, 20, 20, 20, 20, 20],
        [20, 20, 20, 20, 20, 20, 20, 20, 20, 20]]])

In [24]:
array_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
array_2d[0]

array([1, 2, 3])

In [25]:
array_2d[0,1]

2

In [26]:
array_2d[0, :2]

array([1, 2])

In [27]:
array_2d[:-1, :2]

array([[1, 2]])

In [28]:
array_2d[:-1, :2].shape

(1, 2)

In [29]:
array_2d[0, :2].shape

(2,)

In [30]:
array_2d[:,0]

array([1, 4])

In [31]:
array_2d[:,1:]

array([[2, 3],
       [5, 6]])

In [44]:
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
array_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
array_2d_2 = array_2d[:,1:]
array_2d_2

array([[2, 3],
       [5, 6]])

In [46]:
array_2d[0,0] = 0
array_2d

array([[0, 2, 3],
       [4, 5, 6]])

In [48]:
array_2d[0,1] = 0
array_2d_2

array([[0, 3],
       [5, 6]])

In [49]:
array_2d_2[:,:] = 10

In [50]:
array_2d_2

array([[10, 10],
       [10, 10]])

In [51]:
array_2d

array([[ 0, 10, 10],
       [ 4, 10, 10]])

In [55]:
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
array_2d_2 = array_2d[:,1:].copy()
array_2d[0,1] = 0
array_2d_2[1:,:] = 10

In [56]:
array_2d

array([[1, 0, 3],
       [4, 5, 6]])

In [57]:
array_2d_2

array([[ 2,  3],
       [10, 10]])

In [60]:
meu_array = np.arange(5)

nomes = np.array(['Bob', 'Jack', 'Jill', 'Bob', 'Billy'])
nomes

array(['Bob', 'Jack', 'Jill', 'Bob', 'Billy'], dtype='<U5')

In [61]:
meu_array[nomes == 'Bob']

array([0, 3])

In [66]:
[x.startswith('B') for x in nomes]

[True, False, False, True, True]

In [68]:
nomes[[x.startswith('B') for x in nomes]]

array(['Bob', 'Bob', 'Billy'], dtype='<U5')

In [64]:
[x for x in nomes if x.startswith('B')]

['Bob', 'Bob', 'Billy']

In [69]:
nomes.shape

(5,)

In [70]:
nomes.ndim

1

In [71]:
len(nomes)

5

In [72]:
nomes.size

5

In [76]:
nomes.reshape(5,)

array(['Bob', 'Jack', 'Jill', 'Bob', 'Billy'], dtype='<U5')

In [78]:
nomes.shape

(5,)

In [81]:
nomes = nomes.reshape(1,5)
nomes.shape

(1, 5)

In [84]:
arr_ones = np.ones((6, 3))
arr_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [86]:
len((6, 3))

2

In [88]:
arr_ones.ndim

2

In [89]:
len(arr_ones)

6

In [90]:
arr_ones_3d = np.ones((2,6, 3))
arr_ones_3d

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [92]:
arr_ones_3d.ndim

3

In [93]:
len(arr_ones_3d)

2

In [94]:
arr_ones_3d.size

36

In [95]:
array_2d

array([[1, 0, 3],
       [4, 5, 6]])

In [96]:
array_2d - 1

array([[ 0, -1,  2],
       [ 3,  4,  5]])

In [100]:
array_2d = array_2d * -1
array_2d

array([[-1,  0, -3],
       [-4, -5, -6]])

In [102]:
array2 = np.arange(6).reshape((2,3))
array2

array([[0, 1, 2],
       [3, 4, 5]])

In [106]:
array_2d < array2 - 5

array([[False, False, False],
       [ True,  True,  True]])

In [108]:
array_2d * array2

array([[  0,   0,  -6],
       [-12, -20, -30]])

In [107]:
array3 = np.arange(3)
array3.shape

(3,)

In [110]:
array3

array([0, 1, 2])

In [109]:
array_2d * array3

array([[  0,   0,  -6],
       [  0,  -5, -12]])

In [113]:
array_2d > array3 

array([[False, False, False],
       [False, False, False]])