# ANÁLISE DE DADOS COM PYTHON - NUMPY


BIBLIOTECA NUMPY

In [1]:
import numpy as np

In [5]:
#Criar uma matriz unidimensional
array_1 = np.array([1,2,3,4,5,6,7,8,9])
print(array_1)
print(type(array_1))

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [11]:
#criar um array do tipo específico
#criar um array do tipo float 64 bits

array_float = np.array([1,2,3],dtype = np.float64)
print(array_float)
print(type(array_float))

array_float = np.array([1,2,3],dtype = np.int64)
print(array_float)
print(type(array_float))

[1. 2. 3.]
<class 'numpy.ndarray'>
[1 2 3]
<class 'numpy.ndarray'>


In [15]:
#mudar o tipo do array
# Podemos transformar tipos de dados de arrays
array_new = np.array([1,2,3,22.6666, 89.784187])
print(array_new)
array_newInt = array_new.astype(int)
print(array_newInt)

[ 1.        2.        3.       22.6666   89.784187]
[ 1  2  3 22 89]


In [16]:
# podemos fazer o inverso também.
mt5 = np.array([1, 2, 3, 4])
print(mt5)
mt6 = mt5.astype(float)
print(mt6)

[1 2 3 4]
[1. 2. 3. 4.]


In [22]:
# mais de uma dimensão
# cria um matriz bidimensional
array_2d = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(array_2d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [33]:
#criar arrays vazios tipificados
#empty significa que não são inicializados, não que são vazios

array_vazio = np.empty([3,2], dtype = int)
print(array_vazio)
print('--------------')

# cria uma matriz 4x3 com valores zero
array_zeros = np.zeros([4,2])
print(array_zeros)

#com valores igual a um
um = np.ones([6,3])
print(um)

# cria matriz quadrada com diagonal principal com valores 1 e os outros valores zero
diagonal = np.eye(10)
print(diagonal)

[[         0 1072693248]
 [         0 1072693248]
 [         0 1072693248]]
--------------
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [46]:
#valores aleatórios entre zero e um
ale = np.random.random((5))
print(ale)
print('-----------')
#valores aleatórios distr. normal contendo negativos
ale2 = np.random.randn((5))
print(ale2)
print('-----------')
#valores aleatórios 3 x 4
ale3 = (np.random.random((3,4)))
print(ale3)

[0.55510507 0.72883922 0.9473571  0.57349281 0.73442968]
-----------
[-0.19382807  0.87969483  1.5870361  -0.43854676 -0.26311748]
-----------
[[0.03088359 0.28606448 0.04529985 0.69950102]
 [0.05018733 0.47748357 0.53133559 0.00785845]
 [0.45352079 0.62374842 0.53207303 0.70056042]]


In [47]:
#unique remove repetições
j = np.array([11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 18, 19, 20])
j = np.unique(j)
print(j)

[11 12 13 14 15 16 17 18 19 20]


In [54]:
#funções específicas
# cria a matriz bidimensional k
k = np.array([[17,22,43],[27,25,14],[15,24,32]])
# Mostra a matriz k
print(k)
# Mostra um elemento específico da matriz k
print(k[0][1])
# Mostra o tamanho das dimensões da matriz k
print(k.shape)


[[17 22 43]
 [27 25 14]
 [15 24 32]]
22
(3, 3)


In [59]:
#Funções Matemáticas
# Mostra o maior valor da matriz k
print(k.max())
# Mostra o menor valor da matriz k
print(k.min())
# Mostra a soma dos valores da matriz k
print(k.sum())
# Mostra a média dos valores da matriz k
print(k.mean())
# Mostra o valor do desvio padrão (standard deviation) dos valores da matiz k
print(k.std())

43
14
219
24.333333333333332
8.615231988880057


In [60]:
#funções universais, aplicadas a todos os elementos
# Mostra o valor da raiz quadrada de todos elementos
k1 = np.array([1, 4, 9, 16, 25, 36])
print(np.sqrt(k1))
# Mostra o valor do exponencial de todos elementos
print(np.exp(k1))

[1. 2. 3. 4. 5. 6.]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10 4.31123155e+15]


In [82]:
#extração de elementos
m = np.array([1, 2, 3, 4, 5, 6])
# Mostra o elemento da posição 2
m[1]
print("-------")
# Mostra o array criado a partir da posição 0, dois elementos
print(m[0:2])
print("-------")
# Mostra o array criado a partir da 2a posição
# até todo o restante do array
print(m[1:])
print("-------")
# Mostra o array criado a partir da antepenúltima
#posição até o final
print(m[-2:])

-------
[1 2]
-------
[2 3 4 5 6]
-------
[5 6]


In [76]:
#extração de linhas e colunas
l = np.array([[4, 5], [6, 1], [7, 4]])
print(l)
print("-------")
#primeira linha, todas as colunas
l_linha_1 = l[0, :]
print(l_linha_1)
print("-------")
#segunda linha
l_linha_2 = l[1, :]
print(l_linha_2)
print("-------")
#terceira linha
l_linha_3 = l[2, :]
print(l_linha_3)
print("-------")
#todas as linhas, primeira coluna
l_coluna_1 = l[:, 0]
print(l_coluna_1)
print("-------")
#todas as linhas, segunda coluna
l_coluna_2 = l[:, 1]
print(l_coluna_2)

[[4 5]
 [6 1]
 [7 4]]
-------
[4 5]
-------
[6 1]
-------
[7 4]
-------
[4 6 7]
-------
[5 1 4]


# Exercícios - Rodada 01
Numpy - Fatiamento de arrays

2. Crie um array data com a seguinte lista: [1,2,3,4,5,6,7,8,9,10,11,1
2,13,14,15,16]

In [5]:
mt = np.array([1,2,3,4,5,6,7,8,9,10,11,1,2,13,14,15,16])
print(mt)

[ 1  2  3  4  5  6  7  8  9 10 11  1  2 13 14 15 16]


3. Selecione apenas os dados diferentes de 4,6,8,10. Aloque em um 
array chamado data_2.

In [22]:
excluidos = np.arange(4,11,2)
excluidos

array([ 4,  6,  8, 10])

In [25]:
mt_2 = mt[[elemento not in excluidos for elemento in mt]]
mt_2

array([ 1,  2,  3,  5,  7,  9, 11,  1,  2, 13, 14, 15, 16])

4. Crie um array dim2 que tenha 2 dimensões e a lista [1,2,3,4,5] na 
primeira linha e a lista [6,7,8,9,10] na 2a linha

In [27]:
mt_2D = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(mt_2D)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


5. Crie um array chamado dim2_2 que seja uma fatia de dim2 e que 
contenha apenas os valores 3,4,8,9

In [50]:
mt_2D_2 = mt_2D[[0,0,1,1],[2,3,2,3]]
mt_2D_2

array([3, 4, 8, 9])

# Exercícios - Rodada 02
Numpy - Funções úteis

2. Crie um array data com a seguinte lista: [1,2,3,4,5,6,7,8,9,10,11,1
2,13,14,15,16]

In [56]:
data = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
print(data)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


3. Verifique a dimensão, a quantidade de elementos e a forma desse 
array.

In [57]:
#quantidade de elementos
data.size

16

In [58]:
#forma do array
data.shape

(16,)

In [59]:
data.ndim

1

4. Crie um novo array chamado data2, com 4x4 elementos, 
aplicando a função reshape no array data.

In [77]:
data2 = data.reshape((4,4))
print(data2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


5. Verifique a dimensão, a quantidade de elementos e a forma desse 
array.

In [71]:
#quantidade de elementos
data2.size

16

In [72]:
#forma do array
data2.shape

(4, 4)

In [78]:
data2.ndim

2

6. Crie um novo array chamado data_t, que seja a transposição do 
array data2.

In [81]:
data_t = data2.transpose()
print(data_t)

[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


7. Use a função np.flatten() e crie o array data_flat.

In [83]:
data_flat = data2.flatten()
print(data_flat)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


#  Exercícios - Rodada 02
Numpy - Operações com arrays

In [84]:
a = np.array([7])
b = np.array([[4,6,8],[3,5,7]])
c= np.array([3,3,3])
d = np.array([[3,2,1],[1,2,3]])
e = np.array([5,10])


3. Faça as seguintes operações:
a. a * b
b. d - b
c. c + b
d. c + e

In [87]:
mt_a = a * b
print(mt_a)

[[28 42 56]
 [21 35 49]]


In [88]:
mt_b = d-b
print(mt_b)

[[-1 -4 -7]
 [-2 -3 -4]]


In [89]:
mt_c = c+b
print(mt_c)

[[ 7  9 11]
 [ 6  8 10]]


In [90]:
mt_d = c+e
print(mt_d)

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

#  Exercícios - Rodada 03
Numpy - Funções e métodos matemáticos

2. Crie 2 arrays a e b com as seguintes listas:

In [91]:
array_a = np.array([[4,6,8],[3,5,7]])
print(array_a)

[[4 6 8]
 [3 5 7]]


In [93]:
array_b = np.array([[11,13,17],[23,29,31]])
print(array_b)

[[11 13 17]
 [23 29 31]]


3. Use a função cbrt() e calcule a raiz cúbica dos arrays a e b.

In [96]:
c = np.cbrt(array_a)
print(c)

[[1.58740105 1.81712059 2.        ]
 [1.44224957 1.70997595 1.91293118]]


In [97]:
d = np.cbrt(array_b)
print(d)

[[2.22398009 2.35133469 2.57128159]
 [2.84386698 3.07231683 3.14138065]]


4. Calcule a soma cumulativa de a.

In [98]:
e = np.cumsum(array_a)
print(e)

[ 4 10 18 21 26 33]


5. Calcule a média de a e b

In [106]:
f = np.mean(array_a)
print(f)
print('----------')
g = np.mean(array_b)
print(g)

5.5
----------
20.666666666666668


6. Aplique a função np.negative() no array b e soma com b. O que 
aconteceu?

In [110]:
h = np.negative(array_b)
print(h)
print('----------')
i = h + array_b
print(i)

[[-11 -13 -17]
 [-23 -29 -31]]
----------
[[0 0 0]
 [0 0 0]]


#  Exercícios - Rodada 03
Numpy - Funções e métodos matemáticos

7. Crie 2 arrays arrays com as seguintes listas:
a. [[1,2,3],[4,5,6]]
b. [[2,4,6,8],[10,12,14,16]]
c. [[11,13,17],[23,29,31]]
d. [[13,14,5],[19,21,23]]

In [112]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[2,4,6,8],[10,12,14,16]])
c = np.array([[11,13,17],[23,29,31]])
d = np.array([[13,14,5],[19,21,23]])

8. Concatene a e b. O que aconteceu? resp: Vai resultar em um erro, porque as matrizes não têm o mesmo tamanho.

In [121]:
np.concatenate((a,b))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 4

9. Concatene b e c, tanto usando o eixo 0 (linha) quanto o eixo 1 
(coluna).

In [125]:
np.concatenate((b,c),axis=0) 

### Para concatenar os itens seguindo as linhas, as matrizes devem ter o mesmo número de colunas
## em ambas dimensões, neste caso ele faz um empilhamento

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 4 and the array at index 1 has size 3

In [123]:
np.concatenate((b,c),axis=1) 
# neste caso, o numpy gera uma combinação das linhas

array([[ 2,  4,  6,  8, 11, 13, 17],
       [10, 12, 14, 16, 23, 29, 31]])

10. Concatene a e d, tanto usando o eixo 0 (linha) quanto o eixo 1 
(coluna).

In [126]:
np.concatenate((a,d),axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [13, 14,  5],
       [19, 21, 23]])

In [127]:
np.concatenate((a,d),axis=1)

array([[ 1,  2,  3, 13, 14,  5],
       [ 4,  5,  6, 19, 21, 23]])