In [5]:
import numpy as np
my_array = np.array([1,2,3,4,5,6,7,8,9,10])
print(my_array)

In [7]:
type(np.arange(10))


numpy.ndarray

In [9]:
array_1d = np.array([1,2,3])
array_1d

array([1, 2, 3])

In [12]:
array_2d = np.array([[1,2,3], [4,5,6]])
array_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
array_1d_uns = np.ones(10)
array_1d_uns

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [21]:
array_2d_uns = np.ones([2,2,3])
array_2d_uns 

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

# Exercícios de NUMPY
## 1. Abra o Jupyter lab
2. Crie um array data com a seguinte lista: [1,2,3,4,5,6,7,8,9,10,11,1
2,13,14,15,16]


In [22]:
array_1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
array_1 

In [23]:
#ou

In [24]:
array_1 = np.arange(16)
array_1 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

3. Selecione apenas os dados diferentes de 4,6,8,10. Aloque em um 
array chamado data_2.

In [1]:
excluidos = np.arange(4,11,2)
excluidos

NameError: name 'np' is not defined

In [33]:
data_2 = array_1[[elemento not in excluidos for elemento in array_1]] 
data_2

array([ 0,  1,  2,  3,  5,  7,  9, 11, 12, 13, 14, 15])

4. Crie um array dim2 que tenha 2 dimensões e a lista [1,2,3,4,5] na 
primeira linha e a lista [6,7,8,9,10] na 2a linha.


In [7]:
dim_2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
dim_2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

5. Crie um array chamado dim2_2 que seja uma fatia de dim2 e que 
contenha apenas os valores 3,4,8,9.

In [8]:
dim2_2 = dim_2 [[0,0,1,1],[2,3,2,3]]
dim2_2 

array([3, 4, 8, 9])

In [37]:
dim_2.shape

(2, 5)

In [39]:
len(dim_2)

2

In [40]:
dim_2.ndim

2

In [41]:
dim_2.size

10

# Numpy - Funções úteis

1. Abra o Jupyter lab
2. Crie um array data com a seguinte lista: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]
3. Verifique a dimensão, a quantidade de elementos e a forma desse array.

In [51]:
my_array = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
my_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [52]:
my_array.size

16

In [53]:
my_array.ndim

1

In [54]:
my_array.shape

(16,)

4. Crie um novo array chamado data2, com 4x4 elementos, aplicando a função reshape no array data.
5. Verifique a dimensão, a quantidade de elementos e a forma desse array.

In [56]:
data2 = my_array.reshape((4,4))
data2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [57]:
apelido = data2

print(
'''
Dimensões:{}
Quantidade de elementos:{}
Formato do Array: {}
'''.format(data2.ndim,data2.size,data2.shape)

)


Dimensões:2
Quantidade de elementos:16
Formato do Array: (4, 4)



6. Crie um novo array chamado data_t, que seja a transposição do array data2.

In [61]:
data_t = data2.transpose()
data_t

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

7. Use a função np.flatten() e crie o array data_flat.

In [64]:
data_flat = data2.flatten()
data_flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

8. Compare o array data com o array data_flat

# Numpy - Operações com arrays
##1. Abra o Jupyter lab
2. Crie 5 arrays a, b, c, d e e com as seguintes listas:
a. [7]
b. [[4,6,8],[3,5,7]]
c. [3,3,3]
d. [[3,2,1],[1,2,3]]
e. [5,10]

4. O que aconteceu no item d) do último exercício? Explique.

In [75]:
a = np.array([7])
b = np.array([[4,6,8],[3,5,7]])
c= np.array([3,3,3])
d = np.array([[3,2,1],[1,2,3]])
e = np.array([5,10])


3. Faça as seguintes operações:
a. a * b
b. d - b
c. c + b
d. c + e

In [71]:
a * b

array([[28, 42, 56],
       [21, 35, 49]])

In [72]:
d-b

array([[-1, -4, -7],
       [-2, -3, -4]])

In [73]:
c+b

array([[ 7,  9, 11],
       [ 6,  8, 10]])

In [76]:
c+e

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

# Numpy - Funções e métodos matemáticos
1. Abra o Jupyter lab
2. Crie 2 arrays a e b com as seguintes listas:
a. [[4,6,8],[3,5,7]]
b. [[11,13,17],[23,29,31]]
3. Use a função cbrt() e calcule a raiz cúbica dos arrays a e b.
4. Calcule a soma cumulativa de a.
5. Calcule a média de a e b.
6. Aplique a função np.negative() no array b e soma com b. O que 
aconteceu?

In [77]:
a = np.array([[4,6,8],[3,5,7]])
b = np.array([[11,13,17],[23,29,31]])

In [84]:
c = np.cbr(a)
c


AttributeError: module 'numpy' has no attribute 'cbr'

4. Calcule a soma cumulativa de a

In [86]:
np.cumsum(a)

array([ 4, 10, 18, 21, 26, 33], dtype=int32)

In [88]:
np.average(b)

20.666666666666668

In [89]:
np.average(a)

5.5

In [97]:
d = np.mean(a)
e = np.mean(b)
f = (d+e)/2
d

5.5

In [103]:
a = a.flatten()
b = b.flatten()
c = b.copy()

print(a,b,c, sep="\n")

[4 6 8 3 5 7]
[11 13 17 23 29 31]
[11 13 17 23 29 31]


In [101]:
np.concatenate((a,b,c))

array([ 4,  6,  8,  3,  5,  7, 11, 13, 17, 23, 29, 31, 11, 13, 17, 23, 29,
       31])