In [3]:
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_boston, load_iris
from sklearn.datasets import load_diabetes
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np

In [5]:
from sklearn.datasets import load_iris
iris = load_iris(return_X_y = True)

In [6]:
##Separando as variáveis preditoras (X) e das variáveis resposta (y), que é a classificação que queremos obter.

X,y = iris

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state = 0)

In [10]:
##Criando o modelo de classificação
clf = LogisticRegression()
clf.fit(X_train, y_train)

LogisticRegression()

In [11]:
##Aplicando agora o modelo treinado nos dados de teste
predito = clf.predict(X_test)
predito

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 2, 1, 1, 2, 0, 2, 0,
       0])

In [12]:
## Para verificar as probabilidades calculadas para cada item do dataset, usamos a função predict_prob()

clf.predict_proba(X_test)

array([[1.31712097e-04, 5.98577988e-02, 9.40010489e-01],
       [1.33483574e-02, 9.57044530e-01, 2.96071121e-02],
       [9.82912524e-01, 1.70874205e-02, 5.57171200e-08],
       [1.60416049e-06, 2.60970798e-02, 9.73901316e-01],
       [9.68259780e-01, 3.17399846e-02, 2.35807563e-07],
       [2.47803595e-06, 6.75861844e-03, 9.93238904e-01],
       [9.80349295e-01, 1.96506019e-02, 1.03226767e-07],
       [3.00647398e-03, 7.50197194e-01, 2.46796332e-01],
       [1.62160978e-03, 7.41319743e-01, 2.57058647e-01],
       [2.11257123e-02, 9.32808990e-01, 4.60652981e-02],
       [1.02503818e-04, 1.57229173e-01, 8.42668323e-01],
       [7.26131534e-03, 8.08735091e-01, 1.84003594e-01],
       [4.34468234e-03, 7.84036608e-01, 2.11618710e-01],
       [3.22881072e-03, 7.61227577e-01, 2.35543612e-01],
       [4.08986922e-03, 7.03082578e-01, 2.92827552e-01],
       [9.81563629e-01, 1.84362865e-02, 8.42118489e-08],
       [7.00777901e-03, 7.50189106e-01, 2.42803115e-01],
       [1.20065844e-02, 8.31542

In [15]:
##Para avaliar o re3sultado, podemos usar a função classification_report e 
##obter rapidamente as principais métricas de avaliação

from sklearn.metrics import classification_report

In [20]:
print(classification_report(y_test, predito))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      0.94      0.97        18
           2       0.92      1.00      0.96        11

    accuracy                           0.98        45
   macro avg       0.97      0.98      0.98        45
weighted avg       0.98      0.98      0.98        45



# Exercícios

1. Utilize os datasets embutidos no Scikit-Learn crie o conjunto de 
dados cancer, utilizando o argumento return_X_y=True. Pesquise 
sobre o dataset.

In [24]:
from sklearn.datasets import load_breast_cancer
cancer = load_breast_cancer(return_X_y=True)

2. Separe-o em X,y.

In [47]:
X,y = cancer

3. Faça a separação em amostra de treino e teste, deixando 30% 
para teste. Use random_state=42.

In [27]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state = 42)

4. Importe o LogisticRegression, crie o modelo de classificação clf.

In [39]:
clf = LogisticRegression(max_iter = 2500)

5. Treino o modelo aplicando a função fit() aos dados de treino. 

In [40]:
clf.fit(X_train, y_train)

LogisticRegression(max_iter=2500)

6. Faça a predição, aplicando a função predict aos dados X_train, , 
chamando o resultado de predito.

In [48]:
predito = clf.predict(X_train)
predito

array([1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0,

7. Utilize a função de métrica classification_report. O quão bom está 
seu modelo?

In [50]:
print(classification_report(y_train, predito))

              precision    recall  f1-score   support

           0       0.96      0.93      0.95       149
           1       0.96      0.98      0.97       249

    accuracy                           0.96       398
   macro avg       0.96      0.95      0.96       398
weighted avg       0.96      0.96      0.96       398

